// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package backend

type EditTag struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type EditTodo struct {
	ID             string   `json:"id"`
	Text           *string  `json:"text"`
	Done           *bool    `json:"done"`
	Tags           []string `json:"tags"`
	LastEditedByID string   `json:"lastEditedById"`
}

type NewTag struct {
	Name string `json:"name"`
}

type NewTodo struct {
	Text   string   `json:"text"`
	Tags   []string `json:"tags"`
	UserID string   `json:"userId"`
}

type NewUser struct {
	Name string `json:"name"`
}

type SearchResult interface {
	IsSearchResult()
}

type Tag struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (Tag) IsSearchResult() {}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (User) IsSearchResult() {}
